import type { Metadata } from 'next';
import { Cormorant, Roboto } from 'next/font/google';
import './globals.css';
import Nav from '@/app/components/navbar/Nav';

const cormorant = Cormorant({
  subsets: ['latin'],
  variable: '--font-cormorant',
});

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cormorant.variable} ${roboto.variable}`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
